### ISSUE TITLE
Recursive boxing

### ISSUE THREAD

**Issue by void4** [mappum/modbox#4]
Very cool repo. Can boxed code efficiently sandbox another function with it, dynamically?

**Comment by mappum** [comment]
Do you mind elaborating a little on your use case?

You should be able to pass the `modbox` function into the box via the `globals` option, then the boxed code can create child boxes the same way you would do it from outside the box.

**Comment by void4** [comment]
Untrusted code that imports untrusted code etc.
Minimize maximum authority on NPM import trees.

**Comment by mappum** [comment]
That definitely seems possible, and will be an important problem to solve. Although, it may make sense to pull out some components from this repo, I'm not sure if the NPM use-case needs to be hardened against DoS (e.g. malicious while loops), and so doesn't need the performance hit of the gas metering.

**Comment by void4** [comment]
Yeah. It could be an interesting mechanism for genetic programming.

Have you heard of the KeyKOS or Sel4 operating system? KeyKOS came from GNOSIS, an OS designed for tracking resources on mainframes on Tymshare, a pre-internet timesharing system. They allowed processes (always associated with an organizations account) to grant subprocesses resource capabilities, say, for other employees.

**Comment by mappum** [comment]
I've heard of KeyKOS but don't know much about it. This module actually uses code from some of the same people (SES, and the Realms shim, made by @agoric).

**Comment by void4** [comment]
Yeah, that's the connection :) It's fascinating how some things learned in the 70s now slowly come to the surface
